```{r}
library(tidyverse)
library(lme4)
library(Matrix)
library(foreign)
library(lattice)
library(haven)
library(car)
library(sjPlot)
library(mlmRev)
library(rstanarm)
library (bayesplot)
library(ggcorrplot)
```

```{r data}
og_data <- read_dta("ssls99ug13.dta")
only_vals_data <- data.frame(zap_labels(og_data))

label_table <- function(df1 = og_data, df2 = only_vals_data, col) {
  data.frame(value = sort(unique(df1[[col]])), label = names(attr(df1[[col]], "labels")))
}

sexmf_label_table <- label_table(col = "sexmf")
parsc_label_table <- label_table(col = "parsc")
parleft_label_table <- data.frame(value = sort(unique(only_vals_data$parleft)), label = names(attr(og_data$parleft, "labels"))[2:5])
hqual_label_table <- label_table(col = "hqual")

```

```{r encoding and cleaning data}
# Functions to encode values
encode_qna <- function(x) {
  ifelse(x == 1, "Agree", "Disagree")
}
encode_hqual <- function(x) {
  ifelse(x %in% c(1, 2), "NoHighers", "Highers")
}

encode_hqual_numeric <- function(x) {
  ifelse(x == "NoHighers", 1, 0)
}

encode_parsc <- function(x) {
  ifelse(x %in% c(1,2), "Professional", 
         ifelse(x %in% c(3,4,5), "Skilled", 
                ifelse(x %in% c(6,7), "Unskilled", NA)))
}

ssls_data <- only_vals_data %>%
  mutate_at(vars(starts_with("q")), ~encode_qna(.)) %>%
  mutate(hqual = encode_hqual(hqual)) %>%
  mutate(parsc_enc = encode_parsc(parsc),
         hqual_numeric = encode_hqual_numeric(hqual))

ssls_cols <- colnames(ssls_data)[3:length(colnames(ssls_data))-1]

ssls_data[ssls_cols] <- lapply(ssls_data[ssls_cols], factor)

hqual_vals_ratio <- table(ssls_data$hqual)

```

```{r}
nullmodel <- glmer(hqual ~ (1|schoolid), data = ssls_data, family = binomial)
nullmodel_vpc <- pi^2/3
singlemodel <- glm(hqual ~ 1, data = ssls_data, family=binomial)

print(logLik(singlemodel))
print(logLik(nullmodel))
print(summary(nullmodel))

vcm_school_plot_data <- as.data.frame(ranef(nullmodel))

vcm_school_dotplot <- vcm_school_plot_data %>%
  ggplot(aes(x=condval, y=grp, color=term)) +
  geom_dotplot(binaxis="y", stackdir="center", stackratio=1.5,dotsize=0.5) +
  geom_errorbar(aes(xmin=condval + (qnorm(0.025) * condsd),
                    xmax =condval + (qnorm(0.975) * condsd)),
                width = 0.35,
                position = position_dodge(0.9)) +
  labs(x = "Random effect coefficient on likelihood of hqual",
       y = "School") +
  theme(legend.position = "none",
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 15))

```


```{r linear model code}
calculate_vpc <- function(model) {
  var_components <- as.data.frame(VarCorr(model)) %>% select(all_of(c("grp", "vcov", "sdcor")))
  vpc <- var_components[[2]][1]/sum(var_components[[2]])
  return(vpc)
}

lin_model <- lmer(hqual_numeric ~ (1|schoolid), data = ssls_data, REML = FALSE)
summary(lin_model)

vpc_lin_model <- calculate_vpc(lin_model)
```
```{r}
correlation_plot <- model.matrix(~ 0 + hqual + sexmf + parsc_enc + parleft, data = ssls_data) %>%
  cor(use = "pairwise.complete.obs") %>%
  ggcorrplot(show.diag = TRUE, type="full", lab = TRUE, lab_size = 3.5) +
  theme(axis.text = element_text(size = 20))
```



```{r gmler with with multiple explanatory variables}
ssls_multi_mod <- glmer(hqual ~ sexmf + parleft + parsc_enc + (1|schoolid), data = ssls_data, family = binomial, 
                        control = glmerControl(optimizer = "Nelder_Mead", optCtrl=list(maxfun=2e5)))
summary(ssls_multi_mod)

multi_mod_plot_data <- as.data.frame(ranef(ssls_multi_mod))

multi_mod_dotplot <- multi_mod_plot_data %>%
  ggplot(aes(x=condval, y=grp, color=term)) +
  geom_dotplot(binaxis="y", stackdir="center", stackratio=1.5,dotsize=0.5) +
  geom_errorbar(aes(xmin=condval + (qnorm(0.025) * condsd),
                    xmax =condval + (qnorm(0.975) * condsd)),
                width = 0.35,
                position = position_dodge(0.9)) +
  labs(x = "Random effect coefficient on likelihood of hqual",
       y = "School") +
  theme(legend.position = "none",
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 15))
```
```{r}
parsc_hqual_table <- table(ssls_data$parsc, ssls_data$hqual)
chisq_parsc_hqual <- chisq.test(ssls_data$parsc, ssls_data$hqual)
```


```{r models for variance in explanatory variables across countries}
start_time <- Sys.time()
ssls_sex_model <- glmer(hqual ~ parleft + parsc_enc + (1 + sexmf|schoolid), data = ssls_data, family = binomial)
print(Sys.time()- start_time)

summary(ssls_sex_model)
```
```{r model to include q1}
start_time <- Sys.time()
q1_model <- glmer(hqual ~ sexmf + parsc_enc + q1a + q1d + q1f + q1g + q1j + q1k + (1|schoolid), 
                  data = ssls_data, family = binomial, control = glmerControl(optimizer = "Nelder_Mead", optCtrl=list(maxfun=2e5)))
print(Sys.time() - start_time)

summary(q1_model)
```

```{r model to include q2}
start_time <- Sys.time()
q2_model <- glmer(hqual ~ sexmf + parsc_enc + q2a + q2d + q2e + q2g + q2i + (1|schoolid), 
                  data = ssls_data, family = binomial, control = glmerControl(optimizer = "Nelder_Mead", optCtrl=list(maxfun=2e5)))
print(Sys.time()-start_time)

summary(q2_model) 
```


```{r models for variance in explanatory variables}

### THIS TAKES AGES TO RUN ###

start_time <- Sys.time()
ssls_parleft_model <- stan_glmer(hqual ~ sexmf + parleft + parsc_enc + (1 + parleft|schoolid), 
                                 data = ssls_data, family = binomial, seed = 123, iter = 5000, warmup = 2500)
print(Sys.time()-start_time)

# summary(ssls_parleft_model)
```


```{r models for variance in explanatory variables}

### THIS TAKES AGES TO RUN ###

start_time <- Sys.time()
ssls_parsc_model <- stan_glmer(hqual ~ sexmf + parleft + parsc_enc + (1 + parsc_enc|schoolid), 
                               data = ssls_data, family = binomial, seed = 123, iter = 5000, warmup = 2500)
print(Sys.time()-start_time)

# summary(ssls_parsc_model)
```


```{r plotting caterpillar sex}
multi_sex_plot_data <- as.data.frame(ranef(ssls_sex_model))

multi_sex_dotplot <- multi_sex_plot_data %>%
  ggplot(aes(x=condval, y=grp, color = term)) +
  geom_dotplot(binaxis="y", stackdir="center", stackratio=1.5,dotsize=0.5) +
  geom_errorbar(aes(xmin=condval + (qnorm(0.025) * condsd),
                    xmax =condval + (qnorm(0.975) * condsd)),
                width = 0.35,
                position = position_dodge(0.9)) +
  labs(x = "Random effect coefficient on universalism",
       y = "Country") +
  theme(legend.position = "none",
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 17),
        strip.text = element_text(size= 15)) +
  facet_grid(.~term,
             labeller = labeller(term = c("(Intercept)" = "Intercept",
                                          "sexmf1" = "Gender (male)")))
```



```{r}
summary(ssls_data)
```



